### ISSUE TITLE
First file upload to the phone causes the FTC application to crash

### ISSUE THREAD

**Issue by scrippsdragons11691** [TheLostLambda/ftc_http#4]
The ftc robot controller application crashes on the first upload of files from the laptop to the phone.

To reproduce:

Preconditions
    1) phone switched on, FTC app running
    2) Laptop connected over wifi to phone

Steps
    1) run ftc_http_win -u dirName

Observations
    1) After the first few files are uploaded, ftc_http_win reports an error during upload
    2) The phone shows a notification that the FTC app has stopped working

Workaround
    Restart the phone FTC app and any subsequent uploads work

**Comment by TheLostLambda** [comment]
Thank you for the detailed bug report, I'm not in the position to duplicate the bug right now (though I should be soon). Could you check in the meantime if adding the wipe option fixes this (eg `ftc_http_win -wu`)?

**BEFORE ATTEMPTING THIS, BE SURE THAT YOU HAVE BACKED UP ALL OF THE FILES ON THE PHONE**

You can do so with `ftc_http_win -d` and an optional path argument.

Additionally, for how long do subsequent uploads work? How long do you need to wait / what needs to happen for the phone to consider it a "first upload" and breaks again?

Thanks again for the bug report, hopefully I can help out some!

**Comment by scrippsdragons11691** [comment]
Thank you for your reply.

In the meantime, I have found out that the upload fails quite often, not just on the first time.
I did try wiping the phone first and then uploading, but it still fails often.

I have been applying the workaround each time.

If you need some specific test, let me know and I can run it for you.

In the meantime I added a 200 msec delay between each file upload, but the FTC robot controller app still crashes.

**Comment by TheLostLambda** [comment]
Hmm, quite strange. I've tested the app just tonight, a fresh download on my personal phone, and I can't seem to get it to crash.

What version of the app and Android are you running on? What phones are acting as your Robot controller?

Finally, could you try to upload files using the OnBot java web interface and try to replicate the crash that way?

**Comment by scrippsdragons11691** [comment]
I found out that using the OnBot java web interface, the robot controller app crashes sometimes.
I am using a Moto E4
Android version 7.1.1
Robot controller app version is 5.3-64bit

**Comment by TheLostLambda** [comment]
Okay, that is what I was suspecting. It looks like it might be an upstream issue. My application relies on OnBot Java to function, so if that is experiencing issues, then it necessarily trickles down.

1. The first thing I would do is make sure that everything (the robot controller app and Android OS) is as up to date as possible.
2. If the issue persists, I'd try a fresh install of the app.
3. If that doesn't work, you could try wiping and resetting the phones? Though that's a bit extreme.
4. If you or someone you know is able to build the Robot Controller in Android studio, you could try debugging the home-built version of the app. Alternatively, a self-built version could behave slightly differently if you are using Github versions.

Unfortunately, it could be a quite large number of things. Do you have any other models of phone that you could test on?

I wish I could provide some more specific help, but if the issue is also present in OnBot Java, then my options are a bit limited.

It looks like they changed the Github repository this year. Here is the link to try self-building or to open up an upstream bug report: https://github.com/FIRST-Tech-Challenge/SkyStone

Thanks again for all of your debugging work!

**Comment by scrippsdragons11691** [comment]
Given what we have discovered so far, I agree with you that the issue has to be debugged in the robot controller application. 

I tried to look into how to accomplish this and I saw that the OnBot functionality is provided as a jar file as opposed to .java files. I have never debugged the content of jar files. Do you know if this is possible?

If the answer to the above is yes, do you have a suggestion where I could put a breakpoint?

**Comment by TheLostLambda** [comment]
I was able to unpack the jar file (it's a bit like a .zip) and it contains the .java files there. With that being said, I'm not sure how to then rebuild and debug that.

Perhaps when the app crashes, it already outputs an error? You could try just running the app with adb activated and try to take a look at the logs after a crash using the method described here: https://developer.android.com/studio/command-line/logcat.html
