### ISSUE TITLE
New REV Control Hub has a different IP

### ISSUE THREAD

**Issue by egarland** [TheLostLambda/ftc_http#5]
We're using one of the new REV control hubs with an integrated android environment that are being tested this year in a few states and I can't use this tool as is because the control hub has a different IP.   The new control hubs use the IP 192.168.43.1 instead of 192.168.49.1.  Adding an option to toggle between IPs or manually specify an IP is probably a good idea since these will likely be widely used in the future. 

From: https://github.com/ftctechnh/ftc_app/wiki/Writing-an-Op-Mode-with-FTC-Blocks
>  Important Note: If your Robot Controller is a Control Hub, then the address to access the Program & Manage server is "192.168.43.1:8080". Notice the difference in the third octet of the IP addresses (the Control Hub has a "43" instead of a "49").

**Comment by TheLostLambda** [comment]
Thank you very much for hunting this down! I've been trying to debug another team's issue using the integrated robot controller, but I haven't had any hardware to test and hadn't seen that in the documentation anywhere!

I'll get that fixed up soon. I reckon that I could add both IPs to the code and have it automatically try both? With an additional flag for manually specifying an IP?

If you think another approach would work better, please let me know!

Thanks for the helpful bug report!
Brooks J Rady

**Comment by TheLostLambda** [comment]
I think I've got a temporary fix out.

After taking a look at the code, I think that I am going to rewrite this application in some more modern rust in the coming days.

In the meantime, it will automatically try both IPs, but if you are using the REV control hub, there will be a 3 second delay in uploading. I realize that this is quite far from ideal, so hopefully I'll have something much better out soon.

I'm definitely still actively supporting this package and am very glad that it's still of use to people.

I'll release the binaries as soon as I can convince Rust to cross-compile for OSX...

**Comment by TheLostLambda** [comment]
The fix is out here. I actually made it so that this version prefers the REV Control hub, the 3 second delay is present for the old controllers in this version.

Here is the release: https://github.com/TheLostLambda/ftc_http/releases/tag/v1.4.0-beta.0

**Additionally, I'm opening an RFC here**
Should the new version of the app:
1. Require specifying a control hub type / IP
2. Default to one IP, and allow a flag to change the other
3. Automatically decide which IP on each run (3 second delay on every run)
4. Automatically decide which IP and store in temporary file (3 second delay per OS boot)
5. Local configuration file with IP(s)

I'm thinking option 4 and adding a flag for arbitrary IP addresses?
The app will print the IP that it's trying on each run, and only retest the IP if the temporary file is deleted or a new IP is passed in a flag.

Please let me know what you think!

**Comment by TheLostLambda** [comment]
Closing this as version 2.0 is out!
